spring:
  profiles:
    active: local
  application:
    name: mate-match-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql/database?serverTimezone=Asia/Shanghai&autoReconnect=true
    username: username
    password: password
    hikari:
      # 减少最大生命周期，单位毫秒（这里设置为10分钟）
      max-lifetime: 600000
      # 设置合理的连接超时时间
      connection-timeout: 30000
      # 设置最小空闲连接数
      minimum-idle: 5
      # 设置最大连接数
      maximum-pool-size: 15
      # 空闲连接超时时间
      idle-timeout: 300000
  # session 失效时间(分钟)
  session:
    timeout: 3600
  data:
    redis:
      port: 6379
      password: "redis_3YpaAR"
      database: 0
      host: redis
    # 自定义配置
    redisson:
      database: 1
      port: 6379
      password: "redis_3YpaAR"
      host: redis

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 配置springdoc-openapi，用于文档化和访问API
springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha  # 按字母顺序排序操作
  # 配置API文档的访问路径
  api-docs:
    path: /v3/api-docs  # API文档的访问路径
  # 配置API分组，用于组织和管理API
  group-configs:
    - group: 'default'   # API分组名称
      paths-to-match: '/**'  # 匹配所有路径
      packages-to-scan: com.suave.matematch.controller  # 扫描的包，用于自动发现API

# knife4j的增强配置，不需要增强可以不配（详细版见下小节）
knife4j:
  enable: true
  setting:
    language: zh_cn
    # 开启动态请求参数，true-开启，false-关闭
    enable-dynamic-parameter: true

