spring:
  profiles:
    active: local
  application:
    name: mate-match-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql/database?serverTimezone=Asia/Shanghai&autoReconnect=true
    username: username
    password: password
    hikari:
      # 减小最大生命周期，避免长时间连接被数据库关闭
      max-lifetime: 300000      # 从10分钟减少到5分钟
      # 连接超时时间保持不变
      connection-timeout: 30000
      # 稍微减少最小空闲连接，降低资源消耗
      minimum-idle: 3
      # 保持最大连接池大小
      maximum-pool-size: 15
      # 减少空闲连接超时时间
      idle-timeout: 180000      # 从5分钟减少到3分钟
      # 添加以下参数来加强连接有效性检测
      validation-timeout: 5000  # 连接验证超时时间(毫秒)
      leak-detection-threshold: 60000  # 连接泄漏检测阈值(毫秒)
      # 添加连接测试查询
      connection-test-query: SELECT 1
      # 自动提交设置
      auto-commit: true

      # 连接初始化SQL (可选，用于确保连接使用正确的时区等设置)
      # connection-init-sql: "SET NAMES utf8mb4"
  # session 失效时间(分钟)
  session:
    timeout: 3600
  data:
    redis:
      port: 6379
      password: "redis_3YpaAR"
      database: 0
      host: redis
    # 自定义配置
    redisson:
      database: 1
      port: 6379
      password: "redis_3YpaAR"
      host: redis

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 配置springdoc-openapi，用于文档化和访问API
springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha  # 按字母顺序排序操作
  # 配置API文档的访问路径
  api-docs:
    path: /v3/api-docs  # API文档的访问路径
  # 配置API分组，用于组织和管理API
  group-configs:
    - group: 'default'   # API分组名称
      paths-to-match: '/**'  # 匹配所有路径
      packages-to-scan: com.suave.matematch.controller  # 扫描的包，用于自动发现API

# knife4j的增强配置，不需要增强可以不配（详细版见下小节）
knife4j:
  enable: true
  setting:
    language: zh_cn
    # 开启动态请求参数，true-开启，false-关闭
    enable-dynamic-parameter: true

